name: Continuous Integration - Static Analysis (Zig)

on:
  push:
    paths:
      - ".github/workflows/static-analysis-zig.yml"
      - "**/*.zig"
      - "build.zig.zon"
  pull_request:
    paths:
      - ".github/workflows/static-analysis-zig.yml"
      - "**/*.zig"
      - "build.zig.zon"
  workflow_dispatch:

concurrency:
  group: static-analysis-zig-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  zig-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install Zig
        uses: mlugg/setup-zig@v2.2.1
        with:
          version: 0.16.0

      - name: Check formatting
        run: zig fmt --check .

  zig-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install Zig
        uses: mlugg/setup-zig@v2.2.1
        with:
          version: 0.16.0

      - name: Check linting
        run: find . -type f \( -name '*.zig' -o -name '*.zon' \) -print0 | xargs -0 -n1 zig ast-check
