name: Continuous Integration - Static Analysis (GitHub Actions)

on:
  push:
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
  pull_request:
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
  workflow_dispatch:

# Do not include a 'concurrency' block, the one used will come from the callee workflow

jobs:
  github-actions-lint:
    uses: jaudiger/reusable-workflows/.github/workflows/static-analysis-github-actions.yml@17d014bb569a31fe51a5ccc9e756d61977d41a62
    secrets: inherit
